Repository claassenlab/cellpose, pull requests merged in 2024-07, with the labels that each got.

#43 34_new_settings_export_option_in_file_menue
  cellpose/gui/io.py
  cellpose/gui/menus.py
  cellpose/io.py
Labels: size/L

#47 10 display minimap window epic minimap 1
  cellpose/gui/gui.py
  cellpose/gui/guiparts.py
  cellpose/gui/io.py
  cellpose/gui/menus.py
Labels: size/Too_Big

#59 Adds new XXXL label to the PR labeler
  .github/workflows/pr-labeler.yml
Labels: size/XS

#48 11 adjust minimap size
  cellpose/gui/guiparts.py
Labels: size/XXXL

#57 45 Move the view of the viewbox to a given position
  cellpose/gui/gui.py
  cellpose/gui/menus.py
Labels: size/XXL

#61 44 curser position information on mouseclick
  cellpose/gui/guiparts.py
Labels: size/L

#62 46 navigate via the minimap minimap navigation
  cellpose/gui/guiparts.py
Labels: size/S
