Repository claassenlab/cellpose, pull requests merged in 2024-08, with the labels that each got.

#66 New custom stack
  cellpose/gui/gui.py
Labels: size/S

#67 49 new picture import
  cellpose/gui/io.py
Labels: size/L

#60 49 Import multi-layer tiff images and convert them for visualization
  cellpose/gui/io.py
Labels: size/XXL

#68 55 multichannel Initialization
  cellpose/gui/gui.py
  cellpose/gui/io.py
  setup.py
Labels: size/XXXL

#65 40 Position and Size Information of the Drawing Area Contents
  cellpose/gui/gui.py
Labels: size/XL

#70 32 Compute Features
  cellpose/gui/gui.py
  cellpose/gui/io.py
  cellpose/gui/menus.py
  cellpose/io.py
Labels: size/XXXL

#71 42 dynamically adjusting highlight area minimap orientation
  cellpose/gui/gui.py
Labels: size/XS

#72 55 Initialize UI Elements correctly for multichannel TIFF images
  cellpose/gui/gui.py
  cellpose/gui/io.py
Labels: size/Too_Big

#73 #52_54_sliders_and_buttons_functionality
  cellpose/gui/gui.py
  cellpose/gui/io.py
Labels: size/Too_Big

#74 53_custom_color
  cellpose/gui/gui.py
  cellpose/gui/io.py
Labels: size/Too_Big
